export {default as Home} from './Home'
export {default as About} from './About'
export {default as Cart} from './Cart'
export {default as Error} from './Error'
export {default as Landing} from './Landing'